language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
  - 11

sudo: false
git:
  depth: 1000000

script:
  - npm run ci

notifications:
  email:
  - kimmobrunfeldt+git-hours@gmail.com

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
